# Generated by Django 2.1.7 on 2019-02-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('apparentTemp', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('windSpeed', models.FloatField()),
                ('cloudiness', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sunrise', models.DateTimeField()),
                ('sunsetTime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='userdatapoint',
            name='recordedWeather',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.WeatherData'),
        ),
    ]
